### ISSUE TITLE
As a Erasmus+ candidate I can see information about cultural activities/places

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#26]
## Acceptance criteria

- [x] There is a button to access the Cultural Ressources Page
- [x] When clicked, the page will be opened
- [x] On the page will be displayed a grid with flashcards of different activities
- [x] When you click any activity a new page to this activity will be opened (like the courses page)

![Image](https://github.com/Gregsai/SDS-Mamacita/assets/79366518/73b7bdac-3a17-4d5e-b271-c3fd04157345)

## Estimate time
4h

**Comment by DreynN** [comment]
Branch to test: nico-test

**Comment by Gregsai** [comment]
# Comment Greg

Carré pour moi

**Comment by Gregsai** [comment]
@PKCPablo debes aprobar
