### ISSUE TITLE
As a Erasmus+ student I can add information about cultural activities/places

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#27]
## Acceptance criteria

- [x] On the page will be displayed a grid with some flashcards
- [x] When you click a button that says "Create cultural resources" you can add a Name, a Photo, address, useful information (optional)
- [x] The activity will be added

## Estimate time
4h

**Comment by DreynN** [comment]
Branch to test: nico-test

**Comment by Gregsai** [comment]
![Image](https://github.com/Gregsai/SDS-Mamacita/assets/85080566/89a62459-a9b8-4854-b39d-0dd41488de71)
