### ISSUE TITLE
As a Erasmus+ candidate, I can see the official description of the courses offered by the Receiving Institution so I can compose my Learning Agreement.

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#28]
## Acceptance criteria

- [x] When you click the course(s), it opens a new page associated to that course
- [x] On the page it shows the same information of the course page table (Name | Code | Faculty | ECTS | Semester | Language) and also a link to the ECTS card

## Estimate time
2.5h

**Comment by Gregsai** [comment]
# Comment greg

- possible to go to the detailled page once you click on the link. 
- possible to add to favorites inside
- possible to create/add la inside
- fixing of issues (when you added a favourites course to the la, it un favites it). suppose to be solved
- the main area is still blank to welcome the comment 

# Branch : 

greg-test

**Comment by PKCPablo** [comment]
Well done, about the UI it should be something like this:


![Image](https://github.com/Gregsai/SDS-Mamacita/assets/79366518/0bfdcf02-7797-4a63-aa98-c9f1ace0778c)

So when the comment section is done, it makes sense

**Comment by Gregsai** [comment]
i was thinking of keeping information on the left. if we put it above on the larger, it will be a weird line i think. 

With informations on the left, the comment section would be the main part. 

@PKCPablo

**Comment by PKCPablo** [comment]
Okay its seems fair enough, approved
