### ISSUE TITLE
As a Erasmus+ student, I can make a comment about courses offered by the Receiving Institution

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#30]
## Acceptance criteria
- [x] Erasmus+ Student and incoming students can write a comment
- [x] There is displayed a "comment in blank" ready to be filled with text only by the students role mentioned above

![Image](https://github.com/Gregsai/SDS-Mamacita/assets/79366518/522832d6-64a8-4d86-8b68-797f7e38ca47)

## Estimate time
3h

**Comment by Gregsai** [comment]
LA PAGE ? 

And shouldn't Publish be at the bottom ?
