### ISSUE TITLE
Duplicate LAs

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#31]
- [x] There is a button on each LA with a copy icon
- [x] When clicked a new LA should be created with the same courses

![Image](https://github.com/Gregsai/SDS-Mamacita/assets/79366518/6e57174c-4197-4f5b-aeb0-1d47a75530da)

## Estimate time
1.5h

**Comment by Gregsai** [comment]
#31

# Comment greg 

Seems to do the job. 

Improvments : 

- duplicates button are not aligned
-  add the icon : https://icons8.com/icons/set/duplicate
- maybe add the possibility to change the name

**Comment by DreynN** [comment]
- Icon added
- duplicate buttons aligned on the right
