### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by PKCPablo** [Gregsai/SDS-Mamacita#33]
## Courses page
- [x] Same margin on course page than LA page (make margin on course page bigger)
- [x] Narrow columns of table
- [x] The font is larger (Talk with PO about the changes)
- [x] Rows have to be aligned at the center height
- [x] Dropdown menu on language box at add course feature
- [x] The text should display "Create course" instead of "Add course"

## LA page
- [x] Padding between LAs at LA page
- [x] Padding between LA list and create LA button at LA page
- [x] There is a row on the LA table that shows the summary of ECTS

## Estimate time
3h

**Comment by Gregsai** [comment]
# Comment Greg

## Branch 

greg-test

## PR 

To be defined 

## Explanation 

### Course page : 

A) add padding. 

70px between left border and filter, between filter and course list and between course list and right border. The header is not aligned with the content of the page but i think it would be weird to have space between border and logout button ?


![Image](https://github.com/Gregsai/SDS-Mamacita/assets/85080566/e5f36077-a2d4-412d-b6a4-0d9e837b75b2)

B) Narrow columns of table : 

I just made sure that the action buttons stay centered when the size of the window is reduce. For the rest of the columns, the larger font might do the changes automatically


![Image](https://github.com/Gregsai/SDS-Mamacita/assets/85080566/46812fda-639d-4c3a-94af-c2275eb05aae)



### LA page

**Comment by PKCPablo** [comment]
@Gregsai for the A) margin left was nice as it was before, only need to add a little more of margin at the right so it matches with the end of "Cultural resources" text

**Comment by Gregsai** [comment]
but it has to be the same on the left and right ?

**Comment by PKCPablo** [comment]
no need, let left margin as previous versions, and make bigger the right one

**Comment by Gregsai** [comment]
you sure ????? 

![Image](https://github.com/Gregsai/SDS-Mamacita/assets/85080566/4a0adb56-e44d-431e-b1e2-5714e4fc718d)

**Comment by Gregsai** [comment]
and by the way specify precisely what you want. Else you should do it cause i am loosing my time doing thing that will inevitabely be unvalid ...

**Comment by PKCPablo** [comment]
yeah, sorry my bad, thought that with what we talked in class was clear.

Anyway, I have to check the items as I said in class, so if u have any doubts because its not clear, let me know it first

**Comment by PKCPablo** [comment]
> you sure ?????
> 
> ![Image](https://private-user-images.githubusercontent.com/85080566/290866500-4a0adb56-e44d-431e-b1e2-5714e4fc718d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTQ4MjEsIm5iZiI6MTcwMjY1NDUyMSwicGF0aCI6Ii84NTA4MDU2Ni8yOTA4NjY1MDAtNGEwYWRiNTYtZTQ0ZC00MzFlLWIxZTItNTcxNGU0ZmM3MThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE1MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzBiOTdhYzk0NDlmYTEwYTJhMzM4ZTYyMWRjOWQ0ODU4NzE0ZGRjODU4M2RkZWQzMTg1ZDgxNWM5MWYxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p820T6k0aSrccUVdSrvK9AhYtrYly5V4KNKSllqvWus)

Seems fine for me

**Comment by Gregsai** [comment]
ok
